---
title: "Assignment_07_Karthikeyan Chellamuthu"
author: "KarthikeyanChellamuthu"
date: "30/01/2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r}
## Load the ggplot2 package
library(ggplot2)
theme_set(theme_minimal())
```

```{r}
## Set the working directory to the root of your DSC 520 directory

setwd("C:/Users/LENOVO/Desktop/BU/DSC 520 T302-2221 winter 2021-22/GIT-Hub/dsc520-master/data")
heights_df <- read.csv("r4ds/heights.csv")
str(heights_df)

```
```{r}
## Using `cor()` compute correclation coefficients for
## height vs. earn
cor(heights_df$height, heights_df$earn)
```
```{r}
### age vs. earn
cor(heights_df$age, heights_df$earn)
```

```{r}
### ed vs. earn
cor(heights_df$ed, heights_df$earn)
```

```{r}
## Spurious correlation
## The following is data on US spending on science, space, and technology in millions of today's dollars
## and Suicides by hanging strangulation and suffocation for the years 1999 to 2009
## Compute the correlation between these variables
tech_spending <- c(18079, 18594, 19753, 20734, 20831, 23029, 23597, 23584, 25525, 27731, 29449)
suicides <- c(5427, 5688, 6198, 6462, 6635, 7336, 7248, 7491, 8161, 8578, 9000)
```

```{r}
cor(tech_spending, suicides)
```   

