---
title: "Assignment_06_Karthikeyan Chellamuthu"
author: "KarthikeyanChellamuthu"
date: "23/01/2022"
output:
  word_document: default
  pdf_document: default
---

```{r}
## Load the ggplot2 package
library(ggplot2)
theme_set(theme_minimal())
```

```{r}
## Set the working directory to the root of your DSC 520 directory

setwd("C:/Users/LENOVO/Desktop/BU/DSC 520 T302-2221 winter 2021-22/GIT-Hub/dsc520-master/data")
heights_df <- read.csv("r4ds/heights.csv")
str(heights_df)

```
```{r}
# https://ggplot2.tidyverse.org/reference/geom_boxplot.html
## Create boxplots of sex vs. earn and race vs. earn using `geom_point()` and `geom_boxplot()`
## sex vs. earn

ggplot(heights_df, aes(sex, earn))+geom_boxplot(colour = "blue", size = 4.5)
ggplot(heights_df, aes(race, earn))+geom_point()+geom_boxplot(colour = "blue", size = 4.5)
```
```{r}
# https://ggplot2.tidyverse.org/reference/geom_bar.html
## Using `geom_bar()` plot a bar chart of the number of records for each `sex`
ggplot(heights_df, aes(sex)) + geom_bar(colour = "black",fill="blue", width = 0.2)
```
```{r}
## Using `geom_bar()` plot a bar chart of the number of records for each race
ggplot(heights_df, aes(race)) + geom_bar(colour = "black",fill="cyan", width = 0.2)
```
```{r}
## Create a horizontal bar chart by adding `coord_flip()` to the previous plot
ggplot(heights_df, aes(race)) + geom_bar(colour = "black",fill="cyan", width = 0.2)+ coord_flip()

```
```{r}
# https://www.rdocumentation.org/packages/ggplot2/versions/3.3.0/topics/geom_path
## Load the file `"nytimes/covid-19-data/us-states.csv"` and
## assign it to the `covid_df` dataframe
setwd("C:/Users/LENOVO/Desktop/BU/DSC 520 T302-2221 winter 2021-22/GIT-Hub/dsc520-master/data")
covid_df <- read.csv("nytimes/covid-19-data/us-states.csv")

str(covid_df)

## Parse the date column using `as.Date()``
covid_df_dt <- as.Date(covid_df$date)

head(covid_df_dt)
```
```{r}
## Create three dataframes named `california_df`, `ny_df`, and `florida_df`
## containing the data from California, New York, and Florida

california_df <- covid_df[ which( covid_df$state == "California"), ]
ny_df <- covid_df[ which( covid_df$state == "New York"), ]
florida_df <- covid_df[ which( covid_df$state == "Florida"), ]
```

```{r}
## Unique values to obtain the values New York and Florida
unique(covid_df[c("state")])
```

```{r}
## Plot the number of cases in Florida using `geom_line()`
ggplot(data=florida_df, aes(x=date, y=cases, group=2)) + geom_line(color='blue')
```
```{r}
## Add lines for New York and California to the plot

ggplot(data=florida_df, aes(x=date, group=1)) +
  geom_line(aes(y = cases, col=state)) +
  geom_line(data=ny_df, aes(y = cases, col=state)) +
  geom_line(data=california_df, aes(y =cases,  col=state))
```
```{r}
## Use the colors "darkred", "darkgreen", and "steelblue" for Florida, New York, and California
ggplot(data=florida_df, aes(x=date, group=1)) +
  geom_line(aes(y =cases), color = 'darkred') +
  geom_line(data=ny_df, aes(y = cases), color='darkgreen') +
  geom_line(data=california_df, aes(y = cases), color='steelblue')
```
```{r}
## Add a legend to the plot using `scale_colour_manual`
## Add a blank (" ") label to the x-axis and the label "Cases" to the y axis
ggplot(data=florida_df, aes(x=date, group=1)) +
  geom_line(aes(y = cases, col="Florida")) +
  geom_line(data=ny_df, aes(y = cases, col="New York")) +
  geom_line(data=california_df, aes(y =cases,col="California")) +
  scale_colour_manual(values= c('Florida'='darkred',
                                'New York'='darkgreen', 
                                'California'='steelblue' ))+
  xlab("Date") + ylab("Cases")
```
```{r}
## Scale the y axis using `scale_y_log10()`

ggplot(data=florida_df, aes(x=date, group=1)) +
  geom_line(aes(y = cases, col="Florida")) +
  geom_line(data=ny_df, aes(y = cases, col="New York")) +
  geom_line(data=california_df, aes(y =cases,col="California")) +
  scale_colour_manual(values= c('Florida'='darkred',
                                'New York'='darkgreen', 
                                'California'='steelblue' ))+
  xlab("Date") + ylab("Cases")+scale_y_log10()
```

